### ISSUE TITLE
Solver interface for HPIPM

### ISSUE THREAD

**Issue by stephane-caron** [qpsolvers/qpsolvers#126]
The HPIPM solver has Python bindings: https://github.com/giaf/hpipm

**Comment by adamheins** [comment]
I can take a look at this now that https://github.com/giaf/hpipm/pull/135 is merged.

**Comment by stephane-caron** [comment]
Sounds great :+1:  The [developer notes](https://qpsolvers.github.io/qpsolvers/developer-notes.html#adding-a-new-solver) from the docs should cover the steps to add the new solver. I'll be around this month and can help with reviewing the PR, or support if you run into any blocker.

**Comment by stephane-caron** [comment]
Closing this issue as HPIPM was added in #225. Thanks again for this contribution!
