### ISSUE TITLE
3.0.0 install error: arm64 wheels missing in CVXOPT and quadprog

### ISSUE THREAD

**Issue by xedla** [qpsolvers/qpsolvers#189]
On my Mac I can’t install qpsolvers 3.0.0.
Upgrade to 2.8.1 is ok

MacBook Pro,chip M1 Pro
macOS: ventura 13.2.1

Following terminal log

python3 -m pip install qpsolvers==3.0.0 --upgrade

Collecting qpsolvers==3.0.0
 Using cached qpsolvers-3.0.0-py3-none-any.whl (65 kB)
Collecting cvxopt>=1.2.6
 Using cached cvxopt-1.3.0.tar.gz (4.1 MB)
 Preparing metadata (setup.py) ... done
Collecting ecos>=2.0.8
 Using cached ecos-2.0.12-cp311-cp311-macosx_13_0_arm64.whl
Requirement already satisfied: numpy>=1.15.4 in /opt/homebrew/lib/python3.11/site-packages (from qpsolvers==3.0.0) (1.24.2)
Collecting osqp>=0.6.2
 Using cached osqp-0.6.2.post8-cp311-cp311-macosx_13_0_arm64.whl
Collecting quadprog>=0.1.11
 Using cached quadprog-0.1.11.tar.gz (121 kB)
 Installing build dependencies ... done
 Getting requirements to build wheel ... done
 Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: scipy>=1.2.0 in /opt/homebrew/lib/python3.11/site-packages (from qpsolvers==3.0.0) (1.10.1)
Requirement already satisfied: scs>=3.2.0 in /opt/homebrew/lib/python3.11/site-packages (from qpsolvers==3.0.0) (3.2.2)
Collecting qdldl
 Using cached qdldl-0.1.5.post3-cp311-cp311-macosx_13_0_arm64.whl
Building wheels for collected packages: cvxopt, quadprog
 Building wheel for cvxopt (setup.py) ... error
 error: subprocess-exited-with-error

 × python setup.py bdist_wheel did not run successfully.
 │ exit code: 1
 ╰─> [43 lines of output]
     running bdist_wheel
     running build
     running build_py
     creating build
     creating build/lib.macosx-13-arm64-cpython-311
     creating build/lib.macosx-13-arm64-cpython-311/cvxopt
     copying src/python/misc.py -> build/lib.macosx-13-arm64-cpython-311/cvxopt
     copying src/python/_version.py -> build/lib.macosx-13-arm64-cpython-311/cvxopt
     copying src/python/msk.py -> build/lib.macosx-13-arm64-cpython-311/cvxopt
     copying src/python/__init__.py -> build/lib.macosx-13-arm64-cpython-311/cvxopt
     copying src/python/solvers.py -> build/lib.macosx-13-arm64-cpython-311/cvxopt
     copying src/python/cvxprog.py -> build/lib.macosx-13-arm64-cpython-311/cvxopt
     copying src/python/modeling.py -> build/lib.macosx-13-arm64-cpython-311/cvxopt
     copying src/python/info.py -> build/lib.macosx-13-arm64-cpython-311/cvxopt
     copying src/python/coneprog.py -> build/lib.macosx-13-arm64-cpython-311/cvxopt
     copying src/python/printing.py -> build/lib.macosx-13-arm64-cpython-311/cvxopt
     UPDATING build/lib.macosx-13-arm64-cpython-311/cvxopt/_version.py
     set build/lib.macosx-13-arm64-cpython-311/cvxopt/_version.py to '1.3.0'
     running build_ext
     building 'base' extension
     creating build/temp.macosx-13-arm64-cpython-311
     creating build/temp.macosx-13-arm64-cpython-311/src
     creating build/temp.macosx-13-arm64-cpython-311/src/C
     clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/C/base.c -o build/temp.macosx-13-arm64-cpython-311/src/C/base.o
     clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/C/dense.c -o build/temp.macosx-13-arm64-cpython-311/src/C/dense.o
     clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/C/sparse.c -o build/temp.macosx-13-arm64-cpython-311/src/C/sparse.o
     clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk build/temp.macosx-13-arm64-cpython-311/src/C/base.o build/temp.macosx-13-arm64-cpython-311/src/C/dense.o build/temp.macosx-13-arm64-cpython-311/src/C/sparse.o -L/usr/lib -lm -llapack -lblas -o build/lib.macosx-13-arm64-cpython-311/cvxopt/base.cpython-311-darwin.so
     ld: warning: -undefined dynamic_lookup may not work with chained fixups
     building 'blas' extension
     clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/C/blas.c -o build/temp.macosx-13-arm64-cpython-311/src/C/blas.o
     clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk build/temp.macosx-13-arm64-cpython-311/src/C/blas.o -L/usr/lib -lblas -o build/lib.macosx-13-arm64-cpython-311/cvxopt/blas.cpython-311-darwin.so
     ld: warning: -undefined dynamic_lookup may not work with chained fixups
     building 'lapack' extension
     clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/C/lapack.c -o build/temp.macosx-13-arm64-cpython-311/src/C/lapack.o
     clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk build/temp.macosx-13-arm64-cpython-311/src/C/lapack.o -L/usr/lib -llapack -lblas -o build/lib.macosx-13-arm64-cpython-311/cvxopt/lapack.cpython-311-darwin.so
     ld: warning: -undefined dynamic_lookup may not work with chained fixups
     building 'umfpack' extension
     clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -I/usr/local/include -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/C/umfpack.c -o build/temp.macosx-13-arm64-cpython-311/src/C/umfpack.o
     src/C/umfpack.c:23:10: fatal error: 'umfpack.h' file not found
     #include "umfpack.h"
              ^~~~~~~~~~~
     1 error generated.
     error: command '/usr/bin/clang' failed with exit code 1
     [end of output]

 note: This error originates from a subprocess, and is likely not a problem with pip.
 ERROR: Failed building wheel for cvxopt
 Running setup.py clean for cvxopt
 Building wheel for quadprog (pyproject.toml) ... error
 error: subprocess-exited-with-error

 × Building wheel for quadprog (pyproject.toml) did not run successfully.
 │ exit code: 1
 ╰─> [15 lines of output]
     running bdist_wheel
     running build
     running build_ext
     building 'quadprog' extension
     creating build
     creating build/temp.macosx-13-arm64-cpython-311
     creating build/temp.macosx-13-arm64-cpython-311/quadprog
     clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c quadprog/linear-algebra.c -o build/temp.macosx-13-arm64-cpython-311/quadprog/linear-algebra.o
     clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c quadprog/qr-update.c -o build/temp.macosx-13-arm64-cpython-311/quadprog/qr-update.o
     clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c quadprog/quadprog.c -o build/temp.macosx-13-arm64-cpython-311/quadprog/quadprog.o
     quadprog/quadprog.c:198:12: fatal error: 'longintrepr.h' file not found
       #include "longintrepr.h"
                ^~~~~~~~~~~~~~~
     1 error generated.
     error: command '/usr/bin/clang' failed with exit code 1
     [end of output]

 note: This error originates from a subprocess, and is likely not a problem with pip.
 ERROR: Failed building wheel for quadprog
Failed to build cvxopt quadprog
ERROR: Could not build wheels for quadprog, which is required to install pyproject.toml-based projects

**Comment by stephane-caron** [comment]
Thank you for reporting this issue :+1: CVXOPT and quadprog indeed don't provide arm64 wheels, so your system tries to build these solvers from source (and it seems to be missing some Python dependencies to do so).

This will be fixed in the next release https://github.com/qpsolvers/qpsolvers/pull/190

In the meantime, you can use ``qpsolvers==2.8.1`` which has the same features as 3.0.0. (Or learn how to build CVXOPT and quadprog from source on your system.)

**Comment by xedla** [comment]
I've been using it for several months with scs solver
Thanks
