### ISSUE TITLE
Solve LS not optimized for sparsity

### ISSUE THREAD

**Issue by bodono** [qpsolvers/qpsolvers#192]
Hi Stephane, I tired to make this comment on [this](https://scaron.info/blog/conversion-from-least-squares-to-quadratic-programming.html) blogpost but for some reason it wasn't accepting my comment. Since this concerns the `solve_ls` function I thought I would put it here instead.

In certain situations the strategy in the blogpost is not the best way to convert a least-squares problem to a QP. The problem arises when $R$ is very sparse, which comes up a lot in practice. In those cases forming $R^\top W R$ is a) expensive and b) destroys the sparsity since it is likely to be fully dense. A better way to handle this is to introduce a new variable, $y = Rx - s$, and have the objective be $y^\top  W y$, this maintains sparsity all the way through at the expense of only a small increase in problem size and generally will perform *way* better than the first approach if the data are very sparse. It's basically what I do here in this [example](https://www.cvxgrp.org/scs/examples/python/lasso.html#py-lasso).

One caveat is that if R has many more rows than columns then it may be the case that the original strategy is faster, but there is a tradeoff there between the sparsity and the exact number of rows/cols in that case and when to switch from one strategy to the other would require some thought.

**Comment by stephane-caron** [comment]
Thanks Brendan! Yes, the blog is a static website so comments are by e-mail :see_no_evil: (The comments form is a glorified ``mailto:`` that prepares the message in a format I can copy-paste into a file.)

I've updated the post based on your feedback, and started working on https://github.com/qpsolvers/qpsolvers/pull/195 (WIP, should be ready this week) to expose the alternative strategy via a keyword argument. Feel free to chime in here if you have any comment about the post update, or in the PR about the code.
