### ISSUE TITLE
Return `res.x` regardless of solver status, rather than `None`

### ISSUE THREAD

**Issue by rxian** [qpsolvers/qpsolvers#197]
Sometimes OSQP exits with `solved inaccurate` or `maximum iterations reached` (e.g., on large problems; https://osqp.org/docs/interfaces/status_values.html).  Although it is not `solved`, this is fine in my use case, and I still want to get the `res.x` found by OSQP and do stuff with it.

In the current implementation/API, as soon as the exit status is not `solved`, `osqp_solve_problem` would return `None` rather than `res.x`, so I am getting around it by commenting out line 161 in:

https://github.com/qpsolvers/qpsolvers/blob/8d478caee03eaaf0125fe546e6898962839ebcad/qpsolvers/solvers/osqp_.py#L159-L171

It would be great if a parameter/flag could be added to `solve_qp` and `solve_ls` that allows returning solutions with abnormal exit statuses...

**Comment by stephane-caron** [comment]
The PR passes all unit tests. @rxian can you check it out to confirm it fits your use case?

**Comment by rxian** [comment]
Thanks a lot for the fast response!

I see that with the new changes, whether the solver exited normally is now stored in `solution.found`, and `solve_qp` would return `res.x` when `solution.found == True`, e.g., OSQP exited with `solved`; but it would still return `None` e.g., with statuses `solved inaccurate` or `maximum iterations reached` because `solution.found == False` in these cases.

I was thinking if it would be possible to ask `solve_qp` to return the `Solution` object so I could retrieve `res.x` via `solution.x` in these situations, just like the behavior with `scipy.optimize.linprog`, or you would suggest me to just construct `Problem` and call `solve_problem` on it to get the `Solution`, rather than directly calling `solve_qp`?

**Comment by stephane-caron** [comment]
I'd recommend using `solve_problem` to get the full solution rather than the (legacy) `solve_qp`:

```python
problem = Problem(P, q, G, h, A, b, lb, ub)
solution = solve_problem(problem, solver="foobar")
```

I fully agree regarding `solve_ls`, this is a logical next feature :+1: Can you open a separate issue for it?
