### ISSUE TITLE
DAQP: shape of returned solution on QPSUT03 problem

### ISSUE THREAD

**Issue by stephane-caron** [qpsolvers/qpsolvers#201]
While updating https://github.com/qpsolvers/qpsolvers/pull/198 one issue came out with the dual multipliers returned by the DAQP interface on QPSUT03:

```python
from qpsolvers import solve_problem
from qpsolvers.problems import get_qpsut03

problem, expected_solution = get_qpsut03()
solution = solve_problem(problem, solver="daqp")
print(f"{solution.z.shape=}")
print(f"should be: {expected_solution.z.shape=}")
```

Currently this code produces:

```
solution.z.shape=(1,)
should be: expected_solution.z.shape=(0,)
```

This seems related to this part of the interface, which adds a one-dimensional zero inequality when the problem is detected as unconstrained:

```python
    if bupper is None:
        # Unconstrained case
        bupper = np.zeros(1)
        Atot = np.zeros((1, f.size))
```

The problem is not unconstrained here since QPSUT03 has box constraints.

@darnstrom Could you take a look at this case?

**Comment by darnstrom** [comment]
I'm on it! I tried to cheat a bit for the unconstrained case 😬. I will modify the DAQP python interface to deal with unconstrained QPs properly.
