### ISSUE TITLE
MOSEK is unsusable due to the amount of debug traces

### ISSUE THREAD

**Issue by uricohen** [qpsolvers/qpsolvers#210]
The default debug level in mosek [iparam.log](https://docs.mosek.com/latest/pythonapi/parameters.html#mosek.iparam.log) is 10 (in the range [0,Inf]) which makes it unsable in terms of the amount of debug logs in the console. 

I invoked it a few thousand times and for output files >2GB, and the runtime is definitely affected by the heavy i/o...

**Comment by stephane-caron** [comment]
Unfortunately MOSEK is unsupported, which means I can't test things locally.

When `verbose=False` (default) the interface is supposed to set `iparam.log` to 0. But the options might not be passed on correctly.

Can you try calling the solver with `mosek={mosek.iparam.log: 0}`? For example:

```python
x = solve_qp(P, q, G, h, A, b, solver="mosek", mosek={mosek.iparam.log: 0})
```

**Comment by uricohen** [comment]
Maybe I did something wrong, but the syntax was not accepted:
    w = solve_qp(Q, c, G, z, A, b, lb, ub, solver=solver, verbose=False,
mosek={mosek.iparam.log: 0})
    NameError: name 'mosek' is not defined

BTW, once you'll try to support mosek you'll hit an issue that when there
is no solution, it returns an array of size 1, rather than 0:
    ValueError: cannot reshape array of size 1 into shape (127,)
Thanks!

**Comment by stephane-caron** [comment]
> NameError: name 'mosek' is not defined

You'll need to import mosek before that, that is:

```python
import mosek
# ... 
x = solve_qp(P, q, G, h, A, b, solver="mosek", mosek={mosek.iparam.log: 0})
```

> BTW, once you'll try to support mosek you'll hit an issue that when there

For now we don't support MOSEK because we haven't found a way to include it in [continuous integration](https://github.com/qpsolvers/qpsolvers/actions), but we would be happy to merge a PR bringing MOSEK support (ping @mosekadmin or @ulfworsoe?) :slightly_smiling_face:

**Comment by erling-d-andersen** [comment]
We might be able to help you if the continuous integration only requires solution of smallish problems. Otherwise, it will be hard.

**Comment by aszekMosek** [comment]
@stephane-caron  Maybe this can help?

https://docs.mosek.com/latest/faq/faq.html#how-to-use-a-mosek-license-in-a-github-ci-cd-pipeline

Then we can provide you with a license file. I believe that's what CVXPY does. Unless you are referring to some other problems.

**Comment by stephane-caron** [comment]
@erling-d-andersen @aszekMosek Thank you both, yes that would work :ok_hand:

The CI checks that solvers return near-optimal solutions on a set of problems. Small problems are enough, as long as we're able to test all combinations of with/without inequality/equality/box constraints.

**Comment by aszekMosek** [comment]
Related to the parameter passing, please do not run into the same trap as in https://github.com/cvxpy/cvxpy/issues/2023 That is, it is better to only allow Mosek parameters as strings, as was done in https://github.com/cvxpy/cvxpy/pull/2029, so that would be

```
mosek = {"MSK_IPAR_LOG" : 0}
```

It also has the advantage that ``import mosek`` is not necessary.

**Comment by stephane-caron** [comment]
We can't use string parameters right now, given that qpsolvers interface to MOSEK goes through CVXOPT, so I've forward the info in https://github.com/cvxopt/cvxopt/issues/237.

@uricohen Your initial issue should be solved on the current `master` branch. I will release qpsolvers v3.4.0 tomorrow to ship this update to Conda & PyPI users.
