### ISSUE TITLE
what is the model_predictive_control module in  benchmark_model_predictive_control.py?

### ISSUE THREAD

**Issue by candyriver** [qpsolvers/qpsolvers#217]
I try to run the benchmark code ’benchmark_model_predictive_control.py‘ like this :
ipython3 benchmark_model_predictive_control.py
As a result, the error message is 'ModuleNotFoundError: No module named 'model_predictive_control'

**Comment by stephane-caron** [comment]
Thank you for reporting this issue! The corresponding `model_predictive_control.py` is in the [examples](https://github.com/qpsolvers/qpsolvers/tree/01d53ee6d5b8da1ce13951b4d220bdb17a5f42d9/examples) folder, I moved back the benchmark script there. It should work now.

Note that these benchmark scripts are outdated and will disappear in future releases of qpsolvers. For an up-to-date benchmark there is now [qpsolvers_benchmark](https://github.com/qpsolvers/qpsolvers_benchmark).
