### ISSUE TITLE
qpsolvers.available_solvers

### ISSUE THREAD

**Issue by yihang-gao** [qpsolvers/qpsolvers#222]
Hi,
I find that there are many solvers listed in the github page. However, when i run 
qpsolvers.available_solvers
i can only find 4 solvers in my machine. How can i get more solvers? Thanks so much!

**Comment by fabinsch** [comment]
Hi @yihang-gao,
with the following command, you should be able to install all open-source solvers that are available on PyPi at once, as stated in the [docs](https://github.com/qpsolvers/qpsolvers/blob/master/doc/installation.rst#open-source-solvers):
```
pip install "qpsolvers[open_source_solvers]"
```
I hope this helps

**Comment by yihang-gao** [comment]
> 

Thanks so much!
