### ISSUE TITLE
Least squares example in docs do not match the claimed result

### ISSUE THREAD

**Issue by ogencoglu** [qpsolvers/qpsolvers#278]
Apologies for spamming with insignificant issues lately but just in case I will report anyway.

[Least squares doc](https://qpsolvers.github.io/qpsolvers/least-squares.html) has the following example:

```
R = np.array([[1., 2., 0.], [-8., 3., 2.], [0., 1., 1.]])
s = np.array([3., 2., 3.])
G = np.array([[1., 2., 1.], [2., 0., 1.], [-1., 2., -1.]])
h = np.array([3., 2., -2.]).reshape((3,))

x_sol = solve_ls(R, s, G, h, solver="osqp")
print(f"LS solution: x = {x_sol}")
```

First issue is there is a variable name error in docs where `x` is used instead of `x_sol` in print. But more importantly, the found solution is claimed to be `[-0.0530504, 0.0265252, 2.1061008]` where it actually is `[ 0.12997217 -0.06498019  1.74004125]`. Tried with different solvers.

Can you double check this?

Setup:
- python3.11
- qpsolvers==4.2.0
- osqp==0.6.3

**Comment by stephane-caron** [comment]
Nice catch! :fishing_pole_and_fish: Thank you for your careful checking, and apologies that the LS section of the docs needed so many corrections.

I have checked the example and get the same output as you will different solvers. It is fixed in https://github.com/qpsolvers/qpsolvers/pull/279.

**Comment by ogencoglu** [comment]
Awesome! Thank you!
