### ISSUE TITLE
MOSEK license for continuous integration has expired

### ISSUE THREAD

**Issue by stephane-caron** [qpsolvers/qpsolvers#300]
We added MOSEK to the list of supported solvers last year in https://github.com/qpsolvers/qpsolvers/pull/212 (see also https://github.com/qpsolvers/qpsolvers/issues/211). The license shared by MOSEK has now expired, and CI tests fail with: 

```
mosek.Error: rescode.err_license_expired(1001): The license has expired.
```

@aszekMosek Do you want to renew it?

If so you can send me an e-mail like last year and I will update the CI accordingly.

**Comment by aszekMosek** [comment]
Can you please send an email to Mosek support and we'll do it there.

**Comment by stephane-caron** [comment]
Done, license has been updated in https://github.com/qpsolvers/qpsolvers/pull/299 and the CI is back to green :ok_hand:
