### ISSUE TITLE
SolverNotFound in Jupter Notebook

### ISSUE THREAD

**Issue by henryqin1997** [qpsolvers/qpsolvers#314]
I use "pip install qpsolvers[clarabel]" to install qpsolvers with clarabel, but got the following error when use qpsolvers in ipynb environment:

SolverNotFound: found solvers [] but 'clarabel' is not one of them; if 'clarabel' is listed in https://github.com/qpsolvers/qpsolvers#solvers you can run ``pip install qpsolvers[clarabel]``

I tried install and uninstall qpsolvers package with pip and restart the kernel, but it doesn't work. Any idea on how to fix it?

**Comment by stephane-caron** [comment]
What happens in your IPython notebook if you try to import Clarabel directly?

```py
import clarabel
```

**Comment by henryqin1997** [comment]
<img width="1196" alt="image" src="https://github.com/user-attachments/assets/605ae0a8-b447-410c-9d55-db6da1823cff">
That is possible.

**Comment by henryqin1997** [comment]
I rechecked with a separate file running in the terminal with default Python3, and that one works.
<img width="484" alt="image" src="https://github.com/user-attachments/assets/273cecc8-3291-415c-95f4-a6fc62f40981">
<img width="692" alt="image" src="https://github.com/user-attachments/assets/f3f3618f-b054-4118-b270-4db04e2ed3cd">
This may be a specific environment issue with the notebook kernel.
